### ISSUE TITLE
Assert fails in SignalTabread

### ISSUE THREAD

**Issue by pingdynasty** [enzienaudio/heavy#57] opened 2015-12-02 19:28 UTC
SignalTabread.h line 77:

```
#else // HV_SIMD_NONE
  hv_assert(bIn >= 0 && ((hv_uint32_t) bIn < hTable_getAllocated(o->table)));
  *bOut = b[bIn];
#endif
```

The assert fails because bIn == -1.

Patch: https://enzienaudio.com/h/marser/owl/ (version 82)

When I run an emscripten OWL build with HV_SIMD_NONE I get this stack trace

```
Uncaught Assertion failed: bIn >= 0 && ((uint32_t) bIn < hTable_getAllocated(o->table)), at: /home/mars/devel/OwlProgram/Build/HeavySource/SignalTabread.h,78,__hv_tabread_if at Error
    at jsStackTrace (file:///home/mars/devel/OwlProgram/Build/web/patch.js:1173:13)
    at stackTrace (file:///home/mars/devel/OwlProgram/Build/web/patch.js:1190:22)
    at ___assert_fail (file:///home/mars/devel/OwlProgram/Build/web/patch.js:1640:210)
    at ___hv_tabread_if (file:///home/mars/devel/OwlProgram/Build/web/patch.js:11711:3)
    at _hv_owl_process (file:///home/mars/devel/OwlProgram/Build/web/patch.js:10749:3)
    at Array.__ZN10HeavyPatch12processAudioER11AudioBuffer [HeavyPatch::processAudio(AudioBuffer?&)] (file:///home/mars/devel/OwlProgram/Build/web/patch.js:6153:3)
    at _WEB_processBlock (file:///home/mars/devel/OwlProgram/Build/web/patch.js:6815:30)
    at asm._WEB_processBlock (file:///home/mars/devel/OwlProgram/Build/web/patch.js:24093:31)
    at ScriptProcessorNode.that.compute (file:///home/mars/devel/OwlProgram/Build/web/webaudio.js:74:3)
```

**Comment by mhroth** [comment] 2015-12-04 14:18
Ahh the flanger strikes again. I'll take a look!

**Comment by mhroth** [comment] 2015-12-07 09:39
https://enzienaudio.com/h/marser/owl/0zI0f/

**Comment by mhroth** [comment] 2015-12-07 12:30
@pingdynasty are you using any optimisation flags? I cannot reproduce this on my macbook pro :-/ Could there be something platform specific happening?

**Comment by mhroth** [comment] 2016-01-18 15:13
A fix for this has been found and will be released with the new header update.

**Comment by mhroth** [comment] 2016-01-18 22:08
Our new streamlined headers pushed today will fix this issue.

**Closed as completed by mhroth** 2016-01-18 22:08 UTC

**Comment by pingdynasty** [comment] 2016-01-27 19:53
thanks Martin!
