### ISSUE TITLE
Add a warning if patch has numbers at the beginning of any parameter names

### ISSUE THREAD

**Issue by ylevtov** [enzienaudio/heavy#140] opened 2016-11-22 17:53 UTC
Pd won't complain, but it will cause Unity builds (among others?) to fail...

**Comment by mhroth** [comment] 2016-11-22 17:54
@ylevtov could you give an example (e.g. patch)?

**Comment by diplojocus** [comment] 2016-11-22 17:54
duplicate of https://github.com/enzienaudio/heavy/issues/141

**Closed as completed** 2016-11-22 17:54 UTC
Labels: duplicate
