### ISSUE TITLE
3D Spatialized Audio not working

### ISSUE THREAD

**Issue by oddgoo** [enzienaudio/heavy#143] opened 2016-11-26 03:57 UTC
This might be a Unity bug, 

When trying to use Spatial Blend set to 1 (3D) on the AudioSource , everything still sounds as if it was not.
changing the Stereo panning and spread does nothing either. Does Sequencer.cs or OnAudioFilter read "Flatten" the signal ? or is this a Unity bug on 5.4.*?

Thank you!

**Comment by diplojocus** [comment] 2016-11-28 13:45
Actually I think I've found a reason for why the AudioSource settings are not affecting the filters generated by Heavy.

I think I'll need to update the wrapper to generate an AudioClip and use the PCM callback method to fill  the AudioSource data instead of OAFR. Then the spatial blend should work.

I'll get round to it at some point. Perhaps you can try it out and let me know?

**Comment by oddgoo** [comment] 2016-11-29 01:45
Thank you for your answer!

The reason I closed the issue was because I was actually posting this on a completely different unity audio repo, but I'm happy there is relevance here as well! Heavy looks like a great project. I would be happy to integrate and help you test.

**Comment by diemildefreude** [comment] 2017-04-03 08:04
Hi @diplojocus , @oddgoo 

Has either of you gotten this working? I want this to work too, but I'm not sure how to use PCMReaderCallback as @diplojocus described...

**Comment by diplojocus** [comment] 2017-04-03 10:15
hi @diemildefreude this is actually a duplicate of another ticket which has been resolved here: https://github.com/enzienaudio/heavy/issues/112

In particular check out @phembree 's trick for getting around this.

**Closed as completed by diplojocus** 2017-04-03 10:15 UTC
Labels: solved

**Comment by diemildefreude** [comment] 2017-04-03 10:44
@diplojocus Thanks, it works!
