### ISSUE TITLE
[declare] causing crash

### ISSUE THREAD

**Issue by ylevtov** [enzienaudio/heavy#46] opened 2015-06-18 09:54 UTC
A single [declare] object is causing this error:

```
ERROR: dictionary update sequence element #0 has length 5; 2 is required
```

Understandably we don't really need the [declare] object as the abstraction implementation assumes all patches are in the same directory (right?), but some better error handling to inform people that this is the case would be nice.

```
#N canvas 0 22 450 300 10;
#X declare -path foo;
#X obj 138 69 declare -path foo;
```

**Comment by diplojocus** [comment] 2015-06-18 15:52
I get the expected warning:
`Declared path (/tmp/royal-9RtUwA/pd/foo) doesn't exist`
https://enzienaudio.com/h/diplojocus/sine/hrEkU/

Closing as can't reproduce

**Closed as completed by diplojocus** 2015-06-18 15:52 UTC
