### ISSUE TITLE
Subpatches do not take on parent patch's creation arguments

### ISSUE THREAD

**Issue by ylevtov** [enzienaudio/heavy#41] opened 2015-06-05 13:20 UTC
`[f $1]` inside an abstraction with a creation argument works fine, but `[f $1]` inside a sub-patch inside the abstraction throws an error:
`ERROR: dictionary update sequence element #0 has length 4; 2 is required`

Sub-patches cannot have creation arguments of their own, and should implicitly take the creation arguments of their parent patch.

**Comment by mhroth** [comment] 2015-06-09 11:32
#### `patch.pd`

```
#N canvas 0 22 450 300 10;
#X obj 184 71 subpatch 1;
```

#### `subpatch.pd`

```
#N canvas 0 22 450 300 10;
#X obj 207 68 f \$1;
#N canvas 0 22 450 300 (subpatch) 0;
#X obj 191 104 f \$1;
#X restore 252 68 pd;
```

**Comment by mhroth** [comment] 2015-06-09 13:17
Thanks Yuli for correctly identifying the underlying issue. Fixed.

**Comment by ylevtov** [comment] 2015-06-10 13:56
Subpatches do seem to take the parent patch's arguments now, however, if you're casting the argument to a float, subpatches cannot do this if it has not already been done elsewhere in the patch.

The subpatch.pd in the above comment works fine because it has an `[f $1]` object casting $1 to a float before the subpatch does so, however if you remove the `[f $1]` from the abstraction, the compiler returns:

```
ERROR: could not convert string to float: 
```

#### `patch.pd`

```
#N canvas 0 22 450 300 10;
#X obj 184 71 subpatch 1;
```

#### `subpatch.pd`

```
#N canvas 0 22 450 300 10;
#N canvas 0 22 450 300 (subpatch) 0;
#X obj 191 104 f \$1;
#X restore 252 68 pd;
```

**Comment by mhroth** [comment] 2015-06-12 17:35
I can confirm that is a problem. Looking into it.

**Comment by mhroth** [comment] 2015-06-12 18:30
I'm assigning this bug to @diplojocus as it occurs in `pd2hv`. The issue is that `subpatch.pd` does not resolve any arguments because no `$` arguments exist in the top level of `subpatch`. This is a `PdObject.validate()` issue.

**Comment by diplojocus** [comment] 2015-06-18 15:46
Should be fixed and available in the next server update

**Closed as completed by diplojocus** 2015-06-18 15:46 UTC
Labels: bug
